CREATE TABLE `ork_scroll_artwork` (
  `scroll_artwork_id` int unsigned NOT NULL AUTO_INCREMENT,
  `uploader_mundane_id` int unsigned NOT NULL,
  `name` varchar(150) NOT NULL,
  `description` text,
  `tags` varchar(500) DEFAULT NULL,
  `layout_location` enum('full_border','border_left','border_right','border_top','border_bottom','center_image','watermark','top_graphic') NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `original_file_name` varchar(255) NOT NULL,
  `width` smallint unsigned NOT NULL,
  `height` smallint unsigned NOT NULL,
  `file_size` int unsigned NOT NULL,
  `license_signer_name` varchar(200) NOT NULL,
  `license_signed_at` datetime NOT NULL,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `approved_by_mundane_id` int unsigned DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `rejection_reason` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`scroll_artwork_id`),
  KEY `idx_status` (`status`),
  KEY `idx_layout_location` (`layout_location`),
  KEY `idx_uploader_mundane_id` (`uploader_mundane_id`),
  KEY `idx_layout_status` (`layout_location`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
